name: Android Build and Release

on:
  push:
    branches:
      - master # Replace with your main branch name

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk-tools.zip
        unzip -q android-sdk-tools.zip -d $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
        sdkmanager "build-tools;30.0.3" "platforms;android-30" "platform-tools"
        yes | sdkmanager --licenses


    - name: Build and package APK
      run: |
        cd android
        if [ ! -f "gradlew" ]; then gradle wrapper; fi
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace  
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
