name: Android Build and Release

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can adjust the Java version

    - name: Build and package APK
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
